AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - 'Rakefile'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'test/test_helper.rb'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'config/puma.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 3
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 46

# Offense count: 2
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/initializers/dragonfly.rb'
