version: '2'

# build the rails app from local Dockerfile
rails: &rails
  build: .
  depends_on:
    - db
    - store
  volumes:
    - .:/var/www
  links:
    - db
    - store

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
  store:
    image: redis
    ports:
      - '6379:6379'
  app:
    <<: *rails
    command: 'bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - '3000:3000'
  queue:
    <<: *rails
    command: 'bin/sidekiq -c config/sidekiq.yml'
  web:
    image: nginx
    volumes_from:
      - app
    links:
      - app
    volumes:
      - ./config/nginx.conf:/etc/nginx/sites-enabled/waxpoetic
    ports:
      - '80:80'
