default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: waxpoetic_development

test:
  <<: *default
  database: waxpoetic_test

production:
  <<: *default
  database: waxpoetic_production
  host: db
