local:
  service: Disk
  root: <%= Rails.root.join('tmp', 'storage') %>

s3:
  service: S3
  aws_access_key_id: <%= Rails.application.secrets.aws_access_key_id %>
  aws_secret_access_key: <%= Rails.application.secrets.aws_secret_access_key %>
  region: us-east-1a
  bucket: mindbrain-resources
